import distributions_ultradistributions_boundary_values_analytic_theorem_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace distributions_ultradistributions_boundary_values_analytic_theorem_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end distributions_ultradistributions_boundary_values_analytic_theorem_canonical_lane_mathlib
end HautevilleHouse
